#include <ncurses.h>

int main() {
    initscr(); // Start curses mode
    start_color(); // Enable color if needed
    printw("These are the alternate line drawing characters:\n");
    // Enable alternate character set
/*    attron(A_ALTCHARSET);
    // Display a line-drawing characters
    printw("%c\n", ACS_ULCORNER);
    printw("%c\n", ACS_LLCORNER);
    printw("%c\n", ACS_URCORNER);
    printw("%c\n", ACS_LRCORNER);
    printw("%c\n", ACS_LTEE);
    printw("%c\n", ACS_RTEE);
    printw("%c\n", ACS_BTEE);
    printw("%c\n", ACS_TTEE);
    printw("%c\n", ACS_HLINE);
    printw("%c\n", ACS_VLINE);
    printw("%c\n", ACS_PLUS);
    printw("%c\n", ACS_S1);
    printw("%c\n", ACS_S9);
    printw("%c\n", ACS_DIAMOND);
    printw("%c\n", ACS_CKBOARD);
    printw("%c\n", ACS_DEGREE);
    printw("%c\n", ACS_PLMINUS);
    printw("%c\n", ACS_BULLET);
    printw("%c\n", ACS_LARROW);
    printw("%c\n", ACS_RARROW);
    printw("%c\n", ACS_DARROW);
    printw("%c\n", ACS_UARROW);
    printw("%c\n", ACS_BOARD);
    printw("%c\n", ACS_LANTERN);
    printw("%c\n", ACS_BLOCK);
    printw("%c\n", ACS_S3);
    printw("%c\n", ACS_S7);
    printw("%c\n", ACS_LEQUAL);
    printw("%c\n", ACS_GEQUAL);
    printw("%c\n", ACS_PI);
    printw("%c\n", ACS_NEQUAL);
    printw("%c\n", ACS_STERLING);    
*/
    attroff(A_ALTCHARSET);
    printw("ACS_ULCORNER ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_ULCORNER);
    attroff(A_ALTCHARSET);
    printw("ACS_LLCORNER ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_LLCORNER);
    attroff(A_ALTCHARSET);
    printw("ACS_URCORNER ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_URCORNER);
    attroff(A_ALTCHARSET);
    printw("ACS_LRCORNER ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_LRCORNER);
    attroff(A_ALTCHARSET);
    printw("ACS_LTEE ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_LTEE);
    attroff(A_ALTCHARSET);
    printw("ACS_RTEE ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_RTEE);
    attroff(A_ALTCHARSET);
    printw("ACS_BTEE ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_BTEE);
    attroff(A_ALTCHARSET);
    printw("ACS_TTEE ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_TTEE);
    attroff(A_ALTCHARSET);
    printw("ACS_HLINE ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_HLINE);
    attroff(A_ALTCHARSET);
    printw("ACS_VLINE ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_VLINE);
    attroff(A_ALTCHARSET);
    printw("ACS_PLUS ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_PLUS);
    attroff(A_ALTCHARSET);
    printw("ACS_S1 ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_S1);
    attroff(A_ALTCHARSET);
    printw("ACS_S9 ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_S9);
    attroff(A_ALTCHARSET);
    printw("ACS_DIAMOND ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_DIAMOND);
    attroff(A_ALTCHARSET);
    printw("ACS_CKBOARD ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_CKBOARD);
    attroff(A_ALTCHARSET);
    printw("ACS_DEGREE ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_DEGREE);
    attroff(A_ALTCHARSET);
    printw("ACS_PLMINUS ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_PLMINUS);
    attroff(A_ALTCHARSET);
    printw("ACS_BULLET ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_BULLET);
    attroff(A_ALTCHARSET);
    printw("ACS_LARROW ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_LARROW);
    attroff(A_ALTCHARSET);
    printw("ACS_RARROW ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_RARROW);
    attroff(A_ALTCHARSET);
    printw("ACS_DARROW ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_DARROW);
    attroff(A_ALTCHARSET);
    printw("ACS_UARROW ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_UARROW);
    attroff(A_ALTCHARSET);
    printw("ACS_BOARD ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_BOARD);
    attroff(A_ALTCHARSET);
    printw("ACS_LANTERN ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_LANTERN);
    attroff(A_ALTCHARSET);
    printw("ACS_BLOCK ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_BLOCK);
    attroff(A_ALTCHARSET);
    printw("ACS_S3 ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_S3);
    attroff(A_ALTCHARSET);
    printw("ACS_S7 ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_S7);
    attroff(A_ALTCHARSET);
    printw("ACS_LEQUAL ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_LEQUAL);
    attroff(A_ALTCHARSET);
    printw("ACS_GEQUAL ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_GEQUAL);
    attroff(A_ALTCHARSET);
    printw("ACS_PI ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_PI);
    attroff(A_ALTCHARSET);
    printw("ACS_NEQUAL ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_NEQUAL);
    attroff(A_ALTCHARSET);
    printw("ACS_STERLING ");
    attron(A_ALTCHARSET);
    printw("%c\n", ACS_STERLING);
    // Turn off the alternate character set
    attroff(A_ALTCHARSET);
    
    refresh(); // Print it on to the real screen
    getch(); // Wait for user input
    endwin(); // End curses mode

    return 0;
}
